root: true
parserOptions:
  ecmaVersion: 2019
  sourceType: module
env:
  es6: true
  browser: true
  jest: true
plugins:
  - svelte3
extends:
  - eslint:recommended
overrides:
  -
    files:
      - '*.svelte'
    processor: svelte3/svelte3
settings:
  svelte3/compiler-options:
    customElement: true
