root: true
parserOptions:
  ecmaVersion: 2022
  sourceType: module
env:
  es6: true
  browser: true
  jest: true
extends:
  - eslint:recommended
  - plugin:svelte/recommended
rules:
  svelte/valid-compile: 0
# settings:
#   svelte/compiler-options:
#     customElement: true
# overrides:
#   -
#     files: 
#       - "*.svelte"
#     parser: svelte-eslint-parser
#     parserOptions:
#       compilerOptions:
#         customElement: true
